# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Login Systems' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Login Systems

pod 'MOLH' 
end
